// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CinemaCard: typeof import('./src/components/pages/Cinema/CinemaCard.vue')['default']
    CinemasMap: typeof import('./src/components/pages/Cinemas/CinemasMap.vue')['default']
    CinemasMovie: typeof import('./src/components/pages/Cinema/CinemasMovie.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCon: typeof import('element-plus/es')['ElCon']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconTemplate: typeof import('./src/components/common/IconTemplate.vue')['default']
    InputCommon: typeof import('./src/components/common/InputCommon/InputCommon.vue')['default']
    LatestMovie: typeof import('./src/components/home/LatestMovie/LatestMovie.vue')['default']
    LatestMovies: typeof import('./src/components/home/LatestMovies/LatestMovies.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/common/TheFooter.vue')['default']
    TheFooterFeedbackModal: typeof import('./src/components/layouts/TheFooter/TheFooterFeedbackModal.vue')['default']
    TheFooterModal: typeof import('./src/components/layouts/TheFooter/TheFooterModal.vue')['default']
    TheHeader: typeof import('./src/components/layouts/TheHeader/TheHeader.vue')['default']
    TheHeaderAvatar: typeof import('./src/components/layouts/TheHeader/TheHeaderProfile/TheHeaderAvatar.vue')['default']
    TheHeaderProfile: typeof import('./src/components/layouts/TheHeader/TheHeaderProfile/TheHeaderProfile.vue')['default']
    TheSearch: typeof import('./src/components/layouts/TheHeader/TheSearch/TheSearch.vue')['default']
    TheSearchDropdown: typeof import('./src/components/layouts/TheHeader/TheSearchDropdown/TheSearchDropdown.vue')['default']
    TheSearchDropdownItem: typeof import('./src/components/layouts/TheHeader/TheSearchDropdown/TheSearchDropdownItem.vue')['default']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
