// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    LatestMovie: typeof import('./src/components/home/LatestMovie/LatestMovie.vue')['default']
    LatestMovies: typeof import('./src/components/home/LatestMovies/LatestMovies.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/common/TheHeader.vue')['default']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
