// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCon: typeof import('element-plus/es')['ElCon']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    IconTemplate: typeof import('./src/components/common/IconTemplate.vue')['default']
    InputCommon: typeof import('./src/components/common/InputCommon/InputCommon.vue')['default']
    LatestMovie: typeof import('./src/components/home/LatestMovie/LatestMovie.vue')['default']
    LatestMovies: typeof import('./src/components/home/LatestMovies/LatestMovies.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/common/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layouts/DefaultLayout/TheHeader/TheHeader.vue')['default']
    TheSearch: typeof import('./src/components/layouts/DefaultLayout/TheHeader/TheSearch/TheSearch.vue')['default']
    TheSearchDropdown: typeof import('./src/components/layouts/DefaultLayout/TheHeader/TheSearchDropdown/TheSearchDropdown.vue')['default']
    TheSearchDropdownItem: typeof import('./src/components/layouts/DefaultLayout/TheHeader/TheSearchDropdown/TheSearchDropdownItem.vue')['default']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
